import type { Review } from "@/types";

export const reviews: Review[] = [
  {
    id: "r1",
    name: "Анна К.",
    initials: "АК",
    city: "Ростов-на-Дону",
    rating: 5,
    date: "2026-06-18",
    service: "deep-cleaning",
    serviceLabel: "Генеральная уборка",
    text: "Заказывала генеральную уборку перед приездом родителей. Приехали вовремя, отмыли кухню так, что плита выглядит как новая. Очень довольна, буду обращаться ещё.",
    verified: true,
  },
  {
    id: "r2",
    name: "Дмитрий С.",
    initials: "ДС",
    city: "Ростов-на-Дону",
    rating: 5,
    date: "2026-06-10",
    service: "post-renovation",
    serviceLabel: "Уборка после ремонта",
    text: "После ремонта в квартире была строительная пыль везде. Ребята убрали всё за один день, даже следы краски с окон оттёрли. Заехали сразу же. Рекомендую.",
    verified: true,
  },
  {
    id: "r3",
    name: "Марина В.",
    initials: "МВ",
    city: "Ростов-на-Дону",
    rating: 5,
    date: "2026-05-28",
    service: "regular-cleaning",
    serviceLabel: "Поддерживающая уборка",
    text: "Пользуюсь услугой раз в две недели. Всегда один и тот же клинер, всё знает, ключи оставляю спокойно. Цена не меняется, качество стабильное.",
    verified: true,
  },
  {
    id: "r4",
    name: "Игорь П.",
    initials: "ИП",
    city: "Ростов-на-Дону",
    rating: 5,
    date: "2026-05-15",
    service: "furniture-cleaning",
    serviceLabel: "Химчистка мебели",
    text: "Химчистили диван после того, как кот его пометил. Запах ушёл полностью, пятна тоже. Высох за полдня. Спасибо, спасли любимый диван!",
    verified: true,
  },
  {
    id: "r5",
    name: "Елена Т.",
    initials: "ЕТ",
    city: "Ростов-на-Дону",
    rating: 4,
    date: "2026-05-03",
    service: "window-cleaning",
    serviceLabel: "Мытьё окон",
    text: "Помыли все окна в квартире без разводов, даже сетки почистили. Единственное — приехали чуть позже, но предупредили заранее. В целом отлично.",
    verified: true,
  },
  {
    id: "r6",
    name: "Ольга Н.",
    initials: "ОН",
    city: "Ростов-на-Дону",
    rating: 5,
    date: "2026-04-21",
    service: "air-conditioner-cleaning",
    serviceLabel: "Чистка кондиционеров",
    text: "Кондиционер стал неприятно пахнуть. Мастер всё разобрал, промыл, продезинфицировал. Запах исчез, дует свежим воздухом. Очень аккуратно всё сделали.",
    verified: true,
  },
];

export const averageRating =
  Math.round((reviews.reduce((s, r) => s + r.rating, 0) / reviews.length) * 10) / 10;

export const reviewsCount = reviews.length;
