import {
  Sparkles,
  SprayCan,
  Wind,
  Hammer,
  Sofa,
  AppWindow,
  ShieldCheck,
  BadgeCheck,
  Wallet,
  Leaf,
  CreditCard,
  Clock,
  Users,
  Star,
  Home,
  Building2,
  Key,
  Brush,
  Refrigerator,
  CookingPot,
  Microwave,
  Archive,
  Shirt,
  Cat,
  Lamp,
  Award,
  UserCheck,
  GraduationCap,
  Percent,
  Calculator,
  type LucideIcon,
} from "lucide-react";

/** Name → icon map so content files stay serializable (no JSX/functions). */
export const iconRegistry: Record<string, LucideIcon> = {
  sparkles: Sparkles,
  spray: SprayCan,
  wind: Wind,
  hammer: Hammer,
  sofa: Sofa,
  window: AppWindow,
  shield: ShieldCheck,
  badge: BadgeCheck,
  wallet: Wallet,
  leaf: Leaf,
  card: CreditCard,
  clock: Clock,
  users: Users,
  star: Star,
  home: Home,
  building: Building2,
  key: Key,
  brush: Brush,
  refrigerator: Refrigerator,
  oven: CookingPot,
  microwave: Microwave,
  cabinet: Archive,
  shirt: Shirt,
  cat: Cat,
  lamp: Lamp,
  award: Award,
  "user-check": UserCheck,
  graduation: GraduationCap,
  percent: Percent,
  calculator: Calculator,
};

export function getIcon(name: string): LucideIcon {
  return iconRegistry[name] ?? Sparkles;
}
